---
    url: "http://hmg.nflix.com:8080"
    database: 
        host: "10.20.30.5"
        dbname: "nflix"
        user: "postgres"
        password: "qaninja"
    users:
        cat_manager:
            email: "pepper@stark.com"
            pass: "pwd123"